### ISSUE TITLE
Нельзя с первого раза попасть по прямой ссылке в пост

### ISSUE THREAD

**Issue by hudochenkov** [bem-site/bem-forum#109]
При переходе по прямой ссылке на пост (например, http://ru.bem.info/forum/469/) перекидывает на http://ru.bem.info/forum/. Часто из твиттера переходишь и обламываешься, нужно второй раз переходить. Выяснил, что это происходит только если нет куки prevLang. И она постоянно пропадает.

**Comment by tadatuta** [comment]
@hudochenkov Спасибо большое за подробности, сам сталкивался, но закономерность понять не мог. Поправим обязательно!

 // cc @tavriaforever

**Comment by tavriaforever** [comment]
Будет пофикшено на уровне bem-info, спасибо.

**Comment by tavriaforever** [comment]
В продакшене на сайте
