### ISSUE TITLE
Поломалась верстка

### ISSUE THREAD

**Issue by damir180** [bem-site/bem-forum#113]
Поломана верстка на форуме

https://ru.bem.info/forum/-301/

Скрин - http://joxi.ru/brRnVvzhZkq8r1

Браузер - Chrome Версия 44.0.2403.130 m

**Comment by gela-d** [comment]
Привет! Спасибо за репорт. 
Разобрались, история такова: этот пост был давно еще экспортирован из нашего клуба Ярушки, когда она закрывалась. 
Сейчас восстановить исходные комментарии и почему на одном из них эта конвертация сломалась, к сожалению, уже нет возможности. 

Поэтому, к сожалению, пофиксить не получится, но в качестве хоть какой-то доступности контента скидываю скрин нормальных комментариев, которые ломаются 
![123](https://cloud.githubusercontent.com/assets/1333220/9170251/e3e18f66-3f69-11e5-9e87-535f8e834a55.png)

Если нужно, скину тест с ссылками.

**Comment by damir180** [comment]
Привет! Спасибо, текст не нужен... я собственно, увидел проблему и сообщил...

**Comment by gela-d** [comment]
Спасибо!
