### ISSUE TITLE
In `bem.info` clicking on "Talks" redirects to "Forum"

### ISSUE THREAD

**Issue by battaglr** [bem-site/bem-forum#125]
As said in the title, in `bem.info` clicking on "Talks" redirects to "Forum".

Here is a screenshot:

> ![bug](https://cloud.githubusercontent.com/assets/1921409/13066670/424744a2-d447-11e5-95d6-f18a5a69dd7c.png)

Is this the expected behaviour?

**Comment by tadatuta** [comment]
@battaglr yes, Talks is just a part of Forum filtered by label.
But historically it was a separate setup so previous content is kept as archive.

**Comment by battaglr** [comment]
Oh, I see. Are you going to remove the link "Talks" in the near future? If not, it would be nice if the entries with the "Talk" label were unarchived, so they would be easily accessed with just one click.

If that's not possible, feel free to close this issue. :)

**Comment by tadatuta** [comment]
It's not impossible but quite hard. So we'd better spend time to give more talks and put them there ;)

**Comment by battaglr** [comment]
Fair enough :+1:

_Great answer BTW._
