### ISSUE TITLE
Focus switches to search input while writing comment

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem-forum#21]

**Comment by tavriaforever** [comment]
I couldn't repeat, describe you actions

**Comment by tadatuta** [comment]
just typed replay to a post and focus few times moved to search input.

**Comment by veged** [comment]
I think it's because of Option+F shortcut. If you press (and release) Option and after that type anything and after that press "F" or "А" (Russian) then you've got focus in site search.

**Comment by iamstarkov** [comment]
it's very annoying (macos + firefox)

**Comment by alexbaumgertner** [comment]
Confirm bug: mac os + safari

**Comment by qfox** [comment]
Same. win7 chrome
Repeated after pressing alt+"," and then pressing "f" key.

**Comment by qfox** [comment]
@tavriaforever Actually, after pressing Alt+"any key" and then "F"-key. Can't test on mac, but I think Option+"any key" and then "F"-key.

**Comment by tavriaforever** [comment]
Thanks! 
I will do this in nearest time.
