### ISSUE TITLE
Implement alphabet sorting for labels list

### ISSUE THREAD

**Issue by tormozz48** [bem-site/bem-forum#22]

**Comment by tadatuta** [comment]
у нас же сейчас метки сгруппированы по смыслу. их точно нужно сортировать по алфавиту?

**Comment by tavriaforever** [comment]
1. Currently the labels does not sorted 
2. A common and easy to search alphabetically

**Comment by qfox** [comment]
@tadatuta probably, it can be sorted alphabetically inside sense-groups.

@tavriaforever common and easy to search via `cmd+f` ;-)

**Comment by tavriaforever** [comment]
https://github.com/bem/bem-forum/pull/25
