### ISSUE TITLE
Share buttons

### ISSUE THREAD

**Issue by voischev** [bem-site/bem-forum#23]
Есть предложение использовать https://github.com/voischev/bem-social 

Могу что-то допилить, или сделать что-то совместно.
сейчас в планах, по этой либе — добавить иконки, потом буду думать как сделать счетчики

**Comment by tavriaforever** [comment]
You mean to add share icons to each post?

**Comment by voischev** [comment]
yes

**Comment by tavriaforever** [comment]
If you can make a css theme in the style line buttons in bem-components - I will try to implement

**Comment by voischev** [comment]
ok!

**Comment by voischev** [comment]
Hi! is this ok?

**Comment by voischev** [comment]
add yandex share api https://github.com/voischev/bem-social/issues/16

**Comment by voischev** [comment]
Короче Яндекс апи шар умеет только подхватывать данные только из `head` 

Я бы переделал на кастомные или показывал шары только находят в посте
