### ISSUE TITLE
That's strange to see forum topics and issues side by side on github dashboard

### ISSUE THREAD

**Issue by qfox** [bem-site/bem-forum#34]
Can we somehow remove topics from dashboard?

@tadatuta offers to use labels

As I can see to remove forum topics from dashboard they should be closed instantly on creating. And each one should have labels with status (?).

Can we think about it?

**Comment by qfox** [comment]
Probably we can keep them open to show on dashboard if topic waits for an answer. Seems legit.

**Comment by tadatuta** [comment]
@tavriaforever, I think we should add special label `deleted` which only author can add and stop looking at open/closed status at all (still we can use it ourselves for the reason @zxqfox proposed).

// cc @tormozz48

**Comment by qfox** [comment]
Hey there! Some progress on it?

**Comment by tadatuta** [comment]
@zxqfox not yet, we were all working hard to prepare for BEMup

**Comment by tavriaforever** [comment]
We take this issue in sprint for nearest release

**Comment by qfox** [comment]
@tavriaforever Good news, everyone! :+1:

**Comment by tavriaforever** [comment]
https://github.com/bem/bem-forum/pull/49

**Comment by qfox** [comment]
@tavriaforever Харош!

**Comment by qfox** [comment]
@tadatuta Does release date already known?

**Comment by tavriaforever** [comment]
We plan upload the release tomorrow

**Comment by tavriaforever** [comment]
You can try it now! in production bem.info/forum
