### ISSUE TITLE
Показывать заголовок темы в title

### ISSUE THREAD

**Issue by varya** [bem-site/bem-forum#44]
Искать по Форуму можно просто Яндексом. http://yandex.ru/yandsearch?text=%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80&lr=10493&safety=1&site=http%3A%2F%2Fru.bem.info%2Fforum&rnd=24321&csg=0%2C0%2C0%2C0%2C0%2C0%2C0

Но результаты поиска плохочитаемые, тк везде одинаковый title. Сделайте, пожалуйста, чтобы в title был заголовок темы.

Кстати, хотела зарепортить это нажатием на жучка, но он, кажется, не работает.

**Comment by tadatuta** [comment]
Да, делаем, спасибо! С жучком тоже будет лучше (сейчас он просто выставляет метку, но не открывает форму).

**Comment by h4** [comment]
:+1:

**Comment by voischev** [comment]
:+1:

**Comment by tadatuta** [comment]
Нахакатонили же: https://github.com/bem/bem-forum/pull/56
Скоро все будет ;)

**Comment by tavriaforever** [comment]
https://github.com/bem/bem-forum/pull/58

**Comment by tavriaforever** [comment]
В продакшене
