### ISSUE TITLE
Не создается пост

### ISSUE THREAD

**Issue by awinogradov** [bem-site/bem-forum#45]
4 раза попробовал и никак. Ставлю 4 метки. Все заполняю. Грусть:(

**Comment by tavriaforever** [comment]
Больно читать это. Пока воспроизвести не получается. Одно известно что в последний релиз вошел фикс - защита от csrf - в формочки добавили hidden поля с id-шником. Посмотри есть ли такое у тебя при создании поста?

**Comment by awinogradov** [comment]
Есть такое 

``` html
<input type="hidden" name="_csrf" value="0aX4fIki--nsu4LCZCKHtR8kplxI4qDfzuIE">
```

**Comment by tavriaforever** [comment]
We turned on the `debug mode` in github module, collect the logs for a couple of days and will try to understand when the problem happened. Thanks for the info.

**Comment by varya** [comment]
У меня такое очень часто. Поэтому я все посты пишу через интерфейс Гитхаба. Если вам надо что-то проверить, я могу это делать, тк у меня это воспроизводится в  90% случаев. И то же самое с комментированием существующих постов.

**Comment by tavriaforever** [comment]
Thanks for the help!

**Comment by awinogradov** [comment]
Поддерживаю. При создании комментариев та же история.

**Comment by voischev** [comment]
+1 не создается

**Comment by EASemashko** [comment]
+1 не создается

**Comment by tavriaforever** [comment]
Выкатился релиз bem.info с новым поиском. Попробуйте пжл покоментить, написать пост с меткой bem-forum.

**Comment by voischev** [comment]
у меня создается и комментируется

**Comment by EASemashko** [comment]
У меня на работе по-прежнему не выходит комментить и постить. Только через
гитхаб напрямую.

**Comment by awinogradov** [comment]
Не создается по-прежнему:(

**Comment by awinogradov** [comment]
К созданному посту метки добавляются только один раз :) это прикольно))

**Comment by ghost** [comment]
С пятого раза пост добавился. Сыпалась 503 ошибка

**Comment by tavriaforever** [comment]
Кажется разобрались. Попробуйте плз

**Comment by EASemashko** [comment]
Все отлично. А в чем беда была-то?...

**Comment by tavriaforever** [comment]
Сайт лежит не на одной машинке, а на многих одновременно. Страницу и csrf токен пользователь получает c одного сервера, а во время добавления комментария реквест может уходит на другую, которая ожидает другой токен -> не совпадают токены - сервер отвечает отказом, пост/комментарий не добавляется.

**Comment by awinogradov** [comment]
Вроде все ок, создается и редактируется нормально. Закрываю.
