### ISSUE TITLE
Bug on pressing `Page up`/`Page down` in textarea. win7, chrome

### ISSUE THREAD

**Issue by qfox** [bem-site/bem-forum#73]
Found a strange behaviour on pressing `Page up`/`Page down` keys in filled textarea.

After these scrolls caret placed at viewport 0, 0. Why?

After pressing `Page up`: ![image](https://cloud.githubusercontent.com/assets/677518/5982191/c043f5dc-a8d1-11e4-8117-60662bbe4225.png)
After pressing `Page down`: ![image](https://cloud.githubusercontent.com/assets/677518/5982203/d9faf9ee-a8d1-11e4-8e51-6ccf9bdf36b3.png)

**Comment by tadatuta** [comment]
cc @tavriaforever @gela-d

**Comment by tavriaforever** [comment]
Thanks for feedback. This this bug specific for windows OS. We will fix it inside bem-info.

**Comment by tavriaforever** [comment]
In production on bem-info
