### ISSUE TITLE
Сделать комментам id и поправлять ссылки на комменты

### ISSUE THREAD

**Issue by qfox** [bem-site/bem-forum#75]
Такие: https://ru.bem.info/forum/issues/195/

**Comment by tavriaforever** [comment]
Я тоже сегодня подумал об этом)

**Comment by qfox** [comment]
:+1: 

![image](https://cloud.githubusercontent.com/assets/677518/6022754/2a91cf26-abd0-11e4-987e-178257b1c88a.png)

**Comment by sipayRT** [comment]
Вроде, делается вообще легко, а штука оч полезная. Пили, тумбочка ;)

**Comment by tavriaforever** [comment]
Якоря для комментариев в продакшене
