### ISSUE TITLE
Текст вылазит за пределы textarea

### ISSUE THREAD

**Issue by just-boris** [bem-site/bem-forum#89]
Если ее поресайзить за правый уголок, то получится такое

https://yadi.sk/i/ia2ayXO8euVbj

**Comment by tadatuta** [comment]
Спасибо, знаем, исправится с новой версией `bem-components` (см. https://github.com/bem/bem-components/pull/1340)

**Comment by tavriaforever** [comment]
@belozyorcev was fixed this bug and sent PR https://github.com/bem/bem-forum/pull/93
It would be in next bem-info release
