### ISSUE TITLE
Ошибка «не удалось переоткрыть пост»

### ISSUE THREAD

**Issue by h4** [bem-site/bem-forum#90]
https://ru.bem.info/forum/issues/252/ — пост какбы закрыт. Но я торжественно решил добавить свой коммент, на что получил алерт «не удалось переоткрыть пост». Однако комментарий добавился. 

Я примерно понимаю, что произошло под капотом, но как-то всё это антиюзабилительно.

**Comment by tadatuta** [comment]
Спасибо за репорт, поправим.

// cc @gela-d  @tavriaforever

**Comment by gela-d** [comment]
@tavriaforever Коль, глянешь?

**Comment by tavriaforever** [comment]
Миша с 17-00 до 20-00 были проблемы с выкатившимся билдом, в это время форум мог работать не стабильно. Проверил сейчас в продакшене, ошибок не заметил. Спасибо за репорт.

**Comment by h4** [comment]
@tavriaforever как обычно, удачно я зашёл ;)
